server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/test;IFEXISTS=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

    properties:
      hibernate:
        format_sql: true
    open-in-view: false

app:
  admin:
    username: admin
    password: admin123
  jwt:
    secret: "y5h8N2QkV7tRzP3fG4aL9sXc1vB6wYj2K0mF8qD3eH7uJ1nP5rT4oV9bZ6xS8yW3"
    ttl-seconds: 1800

logging:
  level:
    root: INFO
    org.springframework.security: INFO
